#!/usr/bin/env python3
"""
LLM-powered Python to Rust transpiler.
Uses Claude to intelligently translate Python functions to idiomatic Rust.
"""

import re
from pathlib import Path
from anthropic import Anthropic

def transpile_with_llm(python_source: str, function_name: str, context: str = "") -> str:
    """Use Claude to intelligently transpile Python to Rust."""
    
    client = Anthropic()
    
    prompt = f"""You are an expert Python-to-Rust transpiler. Convert this Python function to production-ready Rust.

CONTEXT: {context}

PYTHON SOURCE:
```python
{python_source}
```

REQUIREMENTS:
1. Use PyO3 #[pyfunction] attribute for FFI compatibility
2. Return HashMap<String, String> or PyResult<HashMap<String, String>> as needed
3. For Python-only operations (like discovering models), use PyO3 callbacks:
   ```rust
   fn discover_models() -> PyResult<Vec<HashMap<String, String>>> {{
       Python::with_gil(|py| {{
           let module = PyModule::import_bound(py, "swarm_bridge")?;
           let result = module.getattr("discover_models")?.call0()?;
           Ok(result.extract()?)
       }})
   }}
   ```
4. Use sysinfo crate for system metrics (psutil equivalent)
5. Handle errors with meaningful messages
6. Keep return types as dict/HashMap for compatibility
7. Make it production-ready, not a stub

IMPORTANT: Return ONLY the complete Rust function code. No explanations, no comments about changes. 
Ready to paste into src/lib.rs."""
    
    message = client.messages.create(
        model="claude-3-5-sonnet-20241022",
        max_tokens=2048,
        messages=[{"role": "user", "content": prompt}]
    )
    
    rust_code = message.content[0].text.strip()
    
    # Clean up markdown code blocks if present
    rust_code = re.sub(r'^```rust\n', '', rust_code)
    rust_code = re.sub(r'\n```$', '', rust_code)
    
    return rust_code


def main():
    # Python functions to transpile
    functions = {
        "memory_snapshot": """def memory_snapshot() -> dict:
    \"\"\"Return current memory usage.\"\"\"
    if not _HAS_PSUTIL or psutil is None:
        return {"error": "psutil not installed"}
    proc = psutil.Process(os.getpid())
    vm = psutil.virtual_memory()
    return {
        "process_rss_mb": round(proc.memory_info().rss / (1024 * 1024), 1),
        "system_total_gb": round(vm.total / (1024**3), 1),
        "system_used_percent": vm.percent,
        "system_available_gb": round(vm.available / (1024**3), 1),
    }""",
        
        "status": """def status() -> dict:
    \"\"\"Return bridge availability and configuration.\"\"\"
    return {
        "available": available(),
        "llm_root": _LLM_ROOT,
        "error": _import_error,
        "has_eval": _HAS_EVAL,
        "has_psutil": _HAS_PSUTIL,
        "prompt_count": len(ALL_PROMPTS),
        "categories": list(PROMPT_LIBRARY.keys()),
    }""",
        
        "list_models": """def list_models() -> list[dict]:
    \"\"\"Discover GGUF models using Local_LLM's scanner.\"\"\"
    if not available():
        return []
    return discover_models()""",
        
        "pool_drain": """def pool_drain() -> dict:
    \"\"\"Drain all models from the pool.\"\"\"
    state = _get_state()
    drain_pool(state)
    return {"drained": True, "pool_size": len(state.model_pool)}""",
        
        "run_single_inference": """def run_single_inference(
    model_path: str,
    prompt: str,
    system_prompt: str = "",
    max_tokens: int = 256,
    temperature: float = 0.7,
    n_ctx: int = 2048,
    n_gpu_layers: int = 0,
    preloaded_llm: object | None = None,
) -> dict:
    \"\"\"Run a single inference and return the result dict.\"\"\"
    return run_inference_sync(
        model_path=model_path,
        prompt=prompt,
        system_prompt=system_prompt,
        max_tokens=max_tokens,
        temperature=temperature,
        n_ctx=n_ctx,
        n_gpu_layers=n_gpu_layers,
        preloaded_llm=preloaded_llm,
    )""",
    }
    
    print("🦀 LLM-Powered Python → Rust Transpiler")
    print("=" * 60)
    
    rust_code = "// Auto-generated by LLM transpiler\n// Production-ready Rust implementations\n\n"
    
    for fn_name, python_code in functions.items():
        print(f"\n⏳ Transpiling {fn_name}...")
        
        context = "Translating functions from swarm_bridge.py for PyO3 FFI compatibility"
        
        try:
            transpiled = transpile_with_llm(python_code, fn_name, context)
            rust_code += transpiled + "\n\n"
            print(f"✓ {fn_name} transpiled successfully")
        except Exception as e:
            print(f"✗ Error transpiling {fn_name}: {e}")
            # Fallback with PyO3 callback
            rust_code += f"""#[pyfunction]
fn {fn_name}() -> PyResult<HashMap<String, String>> {{
    // TODO: Implement or use Python callback
    Python::with_gil(|py| {{
        let module = PyModule::import_bound(py, "swarm_bridge")?;
        let result = module.getattr("{fn_name}")?.call0()?;
        Ok(result.extract()?)
    }})
}}

"""
    
    print("\n" + "=" * 60)
    print("Generated Rust code for src/lib.rs:\n")
    print(rust_code)
    
    # Save to file
    output_file = Path(__file__).parent / "generated_rust_code.rs"
    output_file.write_text(rust_code)
    print(f"\n✓ Saved to {output_file}")


if __name__ == "__main__":
    main()
