// src/semantic_fuzzer.rs — Behavioral equivalence detection via differential fuzzing
//
// Port of Analysis/semantic_fuzzer.py
// Detects "Doppelgänger" functions: structurally different but functionally identical.
// Since we can't execute Python functions from Rust, this module works by:
//   1. Generating test inputs from function signatures
//   2. Producing a Python test script that runs both functions and checks equivalence
//   3. Optionally invoking Python to execute the tests

use std::collections::HashMap;
use std::path::Path;

use crate::test_gen;
use crate::types::FunctionRecord;

/// Result of a semantic equivalence check.
#[derive(Debug, Clone)]
pub struct EquivalenceResult {
    pub func_a: String,
    pub func_b: String,
    pub is_equivalent: bool,
    pub reason: String,
}

/// Generate a Python equivalence-test script that tests two functions pairwise.
///
/// This creates a standalone `.py` file that imports both functions,
/// runs them with generated inputs, and prints results.
pub fn generate_equivalence_script(
    func_a: &FunctionRecord,
    func_b: &FunctionRecord,
    iterations: usize,
) -> String {
    let test_cases = test_gen::generate_inputs(func_a);
    let cases_count = test_cases.len().min(iterations);

    let mut script = String::new();
    script.push_str("#!/usr/bin/env python3\n");
    script.push_str("# Auto-generated by X-Ray Semantic Fuzzer\n");
    script.push_str("# Tests behavioral equivalence of two functions\n\n");
    script.push_str("import json, sys\n\n");

    // Embed function A
    script.push_str(&format!("# Function A: {} from {}\n", func_a.name, func_a.file_path));
    for line in func_a.code.lines() {
        script.push_str(line);
        script.push('\n');
    }
    script.push('\n');

    // Rename function A if names collide
    let (name_a, name_b) = if func_a.name == func_b.name {
        let renamed = format!("{}_variant_b", func_b.name);
        script.push_str(&format!(
            "# Function B: {} from {} (renamed to {})\n",
            func_b.name, func_b.file_path, renamed
        ));
        let renamed_code = func_b
            .code
            .replacen(&format!("def {}(", func_b.name), &format!("def {}(", renamed), 1);
        for line in renamed_code.lines() {
            script.push_str(line);
            script.push('\n');
        }
        (func_a.name.clone(), renamed)
    } else {
        script.push_str(&format!(
            "# Function B: {} from {}\n",
            func_b.name, func_b.file_path
        ));
        for line in func_b.code.lines() {
            script.push_str(line);
            script.push('\n');
        }
        (func_a.name.clone(), func_b.name.clone())
    };
    script.push('\n');

    // Generate test harness
    script.push_str("def _safe_call(fn, kwargs):\n");
    script.push_str("    try:\n");
    script.push_str("        return fn(**kwargs), None\n");
    script.push_str("    except Exception as e:\n");
    script.push_str("        return None, type(e).__name__\n");
    script.push('\n');

    script.push_str("results = []\n");
    script.push_str(&format!("test_cases = {}\n\n", generate_test_cases_python(&test_cases[..cases_count])));

    script.push_str("for kwargs in test_cases:\n");
    script.push_str(&format!("    res_a, err_a = _safe_call({}, kwargs)\n", name_a));
    script.push_str(&format!("    res_b, err_b = _safe_call({}, kwargs)\n", name_b));
    script.push_str("    match = (res_a == res_b) and (err_a == err_b)\n");
    script.push_str("    results.append({'input': str(kwargs), 'match': match, 'a': str(res_a), 'b': str(res_b)})\n");
    script.push('\n');

    script.push_str("equivalent = all(r['match'] for r in results)\n");
    script.push_str("print(json.dumps({'equivalent': equivalent, 'tested': len(results), 'results': results}))\n");
    script.push_str("sys.exit(0 if equivalent else 1)\n");

    script
}

/// Generate a Python list literal from test cases.
fn generate_test_cases_python(cases: &[test_gen::TestCase]) -> String {
    let mut items = Vec::new();
    for case in cases {
        let mut kv_pairs = Vec::new();
        for (k, v) in &case.inputs {
            let val_str = match v {
                serde_json::Value::String(s) => format!("\"{}\"", s.replace('\\', "\\\\").replace('"', "\\\"")),
                serde_json::Value::Number(n) => n.to_string(),
                serde_json::Value::Bool(b) => if *b { "True" } else { "False" }.to_string(),
                serde_json::Value::Null => "None".to_string(),
                other => other.to_string(),
            };
            kv_pairs.push(format!("\"{}\": {}", k, val_str));
        }
        items.push(format!("{{{}}}", kv_pairs.join(", ")));
    }
    format!("[{}]", items.join(", "))
}

/// Run a semantic equivalence check by generating and executing a Python script.
///
/// Returns `None` if Python execution is unavailable.
pub fn check_equivalence(
    func_a: &FunctionRecord,
    func_b: &FunctionRecord,
    iterations: usize,
    work_dir: &Path,
) -> Option<EquivalenceResult> {
    let script = generate_equivalence_script(func_a, func_b, iterations);
    let script_path = work_dir.join(format!(
        "_xray_fuzz_{}_{}.py",
        func_a.name, func_b.name
    ));

    std::fs::create_dir_all(work_dir).ok()?;
    std::fs::write(&script_path, &script).ok()?;

    // Try to run the script
    let output = std::process::Command::new("python")
        .arg(&script_path)
        .output()
        .ok()?;

    // Clean up
    let _ = std::fs::remove_file(&script_path);

    let stdout = String::from_utf8_lossy(&output.stdout);
    let is_equivalent = output.status.success();

    Some(EquivalenceResult {
        func_a: func_a.key(),
        func_b: func_b.key(),
        is_equivalent,
        reason: if is_equivalent {
            "Equivalent".to_string()
        } else {
            format!("Divergence detected: {}", stdout.trim())
        },
    })
}

/// Identify candidate pairs for semantic fuzzing from duplicate groups.
///
/// Only pairs from the same structural/near-duplicate groups are tested,
/// since testing all O(n²) pairs would be too expensive.
pub fn select_candidates(
    functions: &[FunctionRecord],
    duplicate_pairs: &[(String, String)],
) -> Vec<(usize, usize)> {
    let key_to_idx: HashMap<String, usize> = functions
        .iter()
        .enumerate()
        .map(|(i, f)| (f.key(), i))
        .collect();

    duplicate_pairs
        .iter()
        .filter_map(|(a, b)| {
            let ia = key_to_idx.get(a)?;
            let ib = key_to_idx.get(b)?;
            Some((*ia, *ib))
        })
        .collect()
}
