"""
_mothership — Vendored modules from Local_LLM mothership.

AUTO-GENERATED by mothership_sync.py — do NOT edit manually.
Synced: 2026-02-20T08:56:22+00:00
"""

from .models import ModelCategory, QuantizationType, WorkerRole, ModelCapabilities, HardwareProfile, LlamaCppStatus, ModelCard, EngineInferenceRequest, EngineInferenceResult, WorkerInferenceRequest, WorkerInferenceResult, WorkerStats, DiscoverModelsRequest, DiscoverModelsResponse, LocalLLMStatus
from .hardware_detection import detect_hardware, format_hardware_profile
from .settings_service import load_settings, save_settings, get_setting, update_setting, SETTINGS_FILENAME, DEFAULT_SETTINGS
