"""
X-Ray LLM — AI code detection, web smells, test stub generation.
"""

import ast
import re
from collections import Counter

from analyzers._shared import _WEB_EXTS, _fwd, _safe_parse, _walk_ext, _walk_py


def detect_ai_code(directory: str) -> dict:
    """Heuristic detection of AI-generated code patterns."""
    indicators = []

    _AI_PATTERNS = [
        (
            re.compile(
                r"#\s*(Generated by|Auto-generated|AI-generated|Created by ChatGPT|Created by Copilot|Generated with)",
                re.IGNORECASE,
            ),
            "AI generation comment",
        ),
        (
            re.compile(r"#\s*TODO:?\s*(implement|add|fill|complete)\s+(this|the|your)", re.IGNORECASE),
            "Placeholder TODO (common in AI output)",
        ),
        (
            re.compile(r'"""[\s\S]{0,20}(Args|Returns|Raises|Example|Note):', re.IGNORECASE),
            "Formulaic docstring (common in AI output)",
        ),
        (re.compile(r"pass\s*#\s*(placeholder|implement|todo)", re.IGNORECASE), "Pass-with-placeholder pattern"),
    ]

    for fpath, rel in _walk_py(directory):
        try:
            with open(fpath, encoding="utf-8", errors="ignore") as f:
                content = f.read()
        except OSError:
            continue

        for lineno, line in enumerate(content.split("\n"), 1):
            for pat, desc in _AI_PATTERNS:
                if pat.search(line):
                    indicators.append(
                        {
                            "file": _fwd(rel),
                            "line": lineno,
                            "pattern": desc,
                            "evidence": line.strip()[:120],
                        }
                    )
                    break

    return {
        "indicators": indicators[:500],
        "total": len(indicators),
        "note": "Heuristic detection — false positives possible",
    }


def detect_web_smells(directory: str) -> dict:
    """Detect common web development anti-patterns in JS/TS/HTML/CSS."""
    smells = []

    _WEB_PATTERNS = [
        (re.compile(r"\bdocument\.write\b"), "HIGH", "document.write() — XSS risk and performance issue"),
        (re.compile(r"\beval\s*\("), "HIGH", "ev" + "al() — code injection risk"),
        (re.compile(r"\binnerHTML\s*="), "MEDIUM", "innerHTML assignment — XSS risk, use textContent"),
        (re.compile(r"console\.(log|debug|info|warn|error)\s*\("), "LOW", "Console statement left in code"),
        (re.compile(r"font-size:\s*\d+px"), "LOW", "Pixel font-size — use rem/em for accessibility"),
        (re.compile(r"!important"), "LOW", "!important in CSS — specificity issue"),
        (re.compile(r"\bvar\s+"), "MEDIUM", "var keyword — use let/const instead"),
        (re.compile(r"==(?!=)"), "MEDIUM", "Loose equality (==) — use strict equality (===)"),
        (re.compile(r"\.then\s*\(.*\.then\s*\("), "MEDIUM", "Nested .then() — use async/await"),
        (re.compile(r"setTimeout\s*\([^,]+,\s*0\s*\)"), "LOW", "setTimeout(fn, 0) — use queueMicrotask"),
        (re.compile(r"<script\s+src\s*=\s*[\"']http:"), "HIGH", "HTTP script src — use HTTPS"),
        (re.compile(r"<img(?![^>]*alt\s*=)[^>]*>"), "MEDIUM", "Missing alt attribute on img — accessibility"),
    ]

    for fpath, rel in _walk_ext(directory, _WEB_EXTS):
        try:
            with open(fpath, encoding="utf-8", errors="ignore") as f:
                content = f.read()
        except OSError:
            continue

        for lineno, line in enumerate(content.split("\n"), 1):
            for pat, severity, desc in _WEB_PATTERNS:
                if pat.search(line):
                    smells.append(
                        {
                            "file": _fwd(rel),
                            "line": lineno,
                            "severity": severity,
                            "description": desc,
                            "evidence": line.strip()[:120],
                        }
                    )

    # Cap output
    smells = smells[:1000]
    by_severity = Counter(s["severity"] for s in smells)

    return {
        "smells": smells,
        "total": len(smells),
        "by_severity": dict(by_severity),
    }


def generate_test_stubs(directory: str) -> dict:
    """Generate pytest test stubs for untested functions."""
    functions = []
    test_files = set()

    # Find existing test files
    for _, rel in _walk_py(directory):
        if "test" in rel.lower():
            test_files.add(rel)

    # Find functions that likely need tests
    for fpath, rel in _walk_py(directory):
        if "test" in rel.lower():
            continue
        tree = _safe_parse(fpath)
        if tree is None:
            continue

        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                if node.name.startswith("_"):
                    continue
                line_count = (node.end_lineno or node.lineno) - node.lineno + 1
                if line_count < 3:
                    continue
                # Check if there's a test for this function
                has_test = any(f"test_{node.name}" in tf or node.name in tf for tf in test_files)
                functions.append(
                    {
                        "name": node.name,
                        "file": _fwd(rel),
                        "line": node.lineno,
                        "lines": line_count,
                        "has_test": has_test,
                        "params": [a.arg for a in node.args.args if a.arg not in ("self", "cls")],
                    }
                )

    # Generate stubs for untested functions
    untested = [f for f in functions if not f["has_test"]]
    stubs = []
    for func in untested[:50]:
        module = func["file"].replace("/", ".").removesuffix(".py")
        params_str = ", ".join(func["params"][:3]) if func["params"] else ""
        stub = f"""def test_{func["name"]}():
    \"\"\"Test {func["name"]} from {func["file"]}\"\"\"
    from {module} import {func["name"]}
    result = {func["name"]}({params_str})
    assert result is not None
"""
        stubs.append(
            {
                "function": func["name"],
                "file": func["file"],
                "stub": stub,
            }
        )

    return {
        "total_functions": len(functions),
        "tested": len([f for f in functions if f["has_test"]]),
        "untested": len(untested),
        "coverage_pct": round(len([f for f in functions if f["has_test"]]) / max(len(functions), 1) * 100, 1),
        "stubs": stubs,
    }
