"""Auto-generated monkey tests for _generated_tests/tests/test_xray_Analysis_test_generator.py by X-Ray v7.0.

Tests function signatures, edge cases, and class instantiation.
"""


def test__generated_tests_tests_test_xray_Analysis_test_generator_test_Analysis_test_generator___init___is_callable_is_callable():
    """Verify test_Analysis_test_generator___init___is_callable exists and is callable."""
    from _generated_tests.tests.test_xray_Analysis_test_generator import test_Analysis_test_generator___init___is_callable
    assert callable(test_Analysis_test_generator___init___is_callable)

def test__generated_tests_tests_test_xray_Analysis_test_generator_test_Analysis_test_generator___init___none_args_is_callable():
    """Verify test_Analysis_test_generator___init___none_args exists and is callable."""
    from _generated_tests.tests.test_xray_Analysis_test_generator import test_Analysis_test_generator___init___none_args
    assert callable(test_Analysis_test_generator___init___none_args)

def test__generated_tests_tests_test_xray_Analysis_test_generator_test_Analysis_test_generator_generate_is_callable_is_callable():
    """Verify test_Analysis_test_generator_generate_is_callable exists and is callable."""
    from _generated_tests.tests.test_xray_Analysis_test_generator import test_Analysis_test_generator_generate_is_callable
    assert callable(test_Analysis_test_generator_generate_is_callable)

def test__generated_tests_tests_test_xray_Analysis_test_generator_test_Analysis_test_generator_generate_none_args_is_callable():
    """Verify test_Analysis_test_generator_generate_none_args exists and is callable."""
    from _generated_tests.tests.test_xray_Analysis_test_generator import test_Analysis_test_generator_generate_none_args
    assert callable(test_Analysis_test_generator_generate_none_args)

def test__generated_tests_tests_test_xray_Analysis_test_generator_test_Analysis_test_generator_generate_return_type_is_callable():
    """Verify test_Analysis_test_generator_generate_return_type exists and is callable."""
    from _generated_tests.tests.test_xray_Analysis_test_generator import test_Analysis_test_generator_generate_return_type
    assert callable(test_Analysis_test_generator_generate_return_type)

def test__generated_tests_tests_test_xray_Analysis_test_generator_test_Analysis_test_generator___init___is_callable_is_callable():
    """Verify test_Analysis_test_generator___init___is_callable exists and is callable."""
    from _generated_tests.tests.test_xray_Analysis_test_generator import test_Analysis_test_generator___init___is_callable
    assert callable(test_Analysis_test_generator___init___is_callable)

def test__generated_tests_tests_test_xray_Analysis_test_generator_test_Analysis_test_generator___init___none_args_is_callable():
    """Verify test_Analysis_test_generator___init___none_args exists and is callable."""
    from _generated_tests.tests.test_xray_Analysis_test_generator import test_Analysis_test_generator___init___none_args
    assert callable(test_Analysis_test_generator___init___none_args)

def test__generated_tests_tests_test_xray_Analysis_test_generator_test_Analysis_test_generator_generate_is_callable_is_callable():
    """Verify test_Analysis_test_generator_generate_is_callable exists and is callable."""
    from _generated_tests.tests.test_xray_Analysis_test_generator import test_Analysis_test_generator_generate_is_callable
    assert callable(test_Analysis_test_generator_generate_is_callable)

def test__generated_tests_tests_test_xray_Analysis_test_generator_test_Analysis_test_generator_generate_none_args_is_callable():
    """Verify test_Analysis_test_generator_generate_none_args exists and is callable."""
    from _generated_tests.tests.test_xray_Analysis_test_generator import test_Analysis_test_generator_generate_none_args
    assert callable(test_Analysis_test_generator_generate_none_args)

def test__generated_tests_tests_test_xray_Analysis_test_generator_test_Analysis_test_generator_generate_return_type_is_callable():
    """Verify test_Analysis_test_generator_generate_return_type exists and is callable."""
    from _generated_tests.tests.test_xray_Analysis_test_generator import test_Analysis_test_generator_generate_return_type
    assert callable(test_Analysis_test_generator_generate_return_type)

def test__generated_tests_tests_test_xray_Analysis_test_generator_test_Analysis_test_generator___init___is_callable_is_callable():
    """Verify test_Analysis_test_generator___init___is_callable exists and is callable."""
    from _generated_tests.tests.test_xray_Analysis_test_generator import test_Analysis_test_generator___init___is_callable
    assert callable(test_Analysis_test_generator___init___is_callable)

def test__generated_tests_tests_test_xray_Analysis_test_generator_test_Analysis_test_generator___init___none_args_is_callable():
    """Verify test_Analysis_test_generator___init___none_args exists and is callable."""
    from _generated_tests.tests.test_xray_Analysis_test_generator import test_Analysis_test_generator___init___none_args
    assert callable(test_Analysis_test_generator___init___none_args)

def test__generated_tests_tests_test_xray_Analysis_test_generator_test_Analysis_test_generator_detect_project_type_is_callable_is_callable():
    """Verify test_Analysis_test_generator_detect_project_type_is_callable exists and is callable."""
    from _generated_tests.tests.test_xray_Analysis_test_generator import test_Analysis_test_generator_detect_project_type_is_callable
    assert callable(test_Analysis_test_generator_detect_project_type_is_callable)

def test__generated_tests_tests_test_xray_Analysis_test_generator_test_Analysis_test_generator_detect_project_type_return_type_is_callable():
    """Verify test_Analysis_test_generator_detect_project_type_return_type exists and is callable."""
    from _generated_tests.tests.test_xray_Analysis_test_generator import test_Analysis_test_generator_detect_project_type_return_type
    assert callable(test_Analysis_test_generator_detect_project_type_return_type)

def test__generated_tests_tests_test_xray_Analysis_test_generator_test_Analysis_test_generator_detect_project_type_high_complexity_is_callable():
    """Verify test_Analysis_test_generator_detect_project_type_high_complexity exists and is callable."""
    from _generated_tests.tests.test_xray_Analysis_test_generator import test_Analysis_test_generator_detect_project_type_high_complexity
    assert callable(test_Analysis_test_generator_detect_project_type_high_complexity)

def test__generated_tests_tests_test_xray_Analysis_test_generator_test_Analysis_test_generator_generate_is_callable_is_callable():
    """Verify test_Analysis_test_generator_generate_is_callable exists and is callable."""
    from _generated_tests.tests.test_xray_Analysis_test_generator import test_Analysis_test_generator_generate_is_callable
    assert callable(test_Analysis_test_generator_generate_is_callable)

def test__generated_tests_tests_test_xray_Analysis_test_generator_test_Analysis_test_generator_generate_none_args_is_callable():
    """Verify test_Analysis_test_generator_generate_none_args exists and is callable."""
    from _generated_tests.tests.test_xray_Analysis_test_generator import test_Analysis_test_generator_generate_none_args
    assert callable(test_Analysis_test_generator_generate_none_args)

def test__generated_tests_tests_test_xray_Analysis_test_generator_test_Analysis_test_generator_generate_return_type_is_callable():
    """Verify test_Analysis_test_generator_generate_return_type exists and is callable."""
    from _generated_tests.tests.test_xray_Analysis_test_generator import test_Analysis_test_generator_generate_return_type
    assert callable(test_Analysis_test_generator_generate_return_type)

def test__generated_tests_tests_test_xray_Analysis_test_generator_test_Analysis_test_generator_generate_high_complexity_is_callable():
    """Verify test_Analysis_test_generator_generate_high_complexity exists and is callable."""
    from _generated_tests.tests.test_xray_Analysis_test_generator import test_Analysis_test_generator_generate_high_complexity
    assert callable(test_Analysis_test_generator_generate_high_complexity)

def test__generated_tests_tests_test_xray_Analysis_test_generator_test_Analysis_test_generator_GeneratedTestFile_is_class_is_callable():
    """Verify test_Analysis_test_generator_GeneratedTestFile_is_class exists and is callable."""
    from _generated_tests.tests.test_xray_Analysis_test_generator import test_Analysis_test_generator_GeneratedTestFile_is_class
    assert callable(test_Analysis_test_generator_GeneratedTestFile_is_class)

def test__generated_tests_tests_test_xray_Analysis_test_generator_test_Analysis_test_generator_TestGenReport_is_class_is_callable():
    """Verify test_Analysis_test_generator_TestGenReport_is_class exists and is callable."""
    from _generated_tests.tests.test_xray_Analysis_test_generator import test_Analysis_test_generator_TestGenReport_is_class
    assert callable(test_Analysis_test_generator_TestGenReport_is_class)

def test__generated_tests_tests_test_xray_Analysis_test_generator_test_Analysis_test_generator_PythonTestGenerator_is_class_is_callable():
    """Verify test_Analysis_test_generator_PythonTestGenerator_is_class exists and is callable."""
    from _generated_tests.tests.test_xray_Analysis_test_generator import test_Analysis_test_generator_PythonTestGenerator_is_class
    assert callable(test_Analysis_test_generator_PythonTestGenerator_is_class)

def test__generated_tests_tests_test_xray_Analysis_test_generator_test_Analysis_test_generator_PythonTestGenerator_has_methods_is_callable():
    """Verify test_Analysis_test_generator_PythonTestGenerator_has_methods exists and is callable."""
    from _generated_tests.tests.test_xray_Analysis_test_generator import test_Analysis_test_generator_PythonTestGenerator_has_methods
    assert callable(test_Analysis_test_generator_PythonTestGenerator_has_methods)

def test__generated_tests_tests_test_xray_Analysis_test_generator_test_Analysis_test_generator_JSTSTestGenerator_is_class_is_callable():
    """Verify test_Analysis_test_generator_JSTSTestGenerator_is_class exists and is callable."""
    from _generated_tests.tests.test_xray_Analysis_test_generator import test_Analysis_test_generator_JSTSTestGenerator_is_class
    assert callable(test_Analysis_test_generator_JSTSTestGenerator_is_class)

def test__generated_tests_tests_test_xray_Analysis_test_generator_test_Analysis_test_generator_JSTSTestGenerator_has_methods_is_callable():
    """Verify test_Analysis_test_generator_JSTSTestGenerator_has_methods exists and is callable."""
    from _generated_tests.tests.test_xray_Analysis_test_generator import test_Analysis_test_generator_JSTSTestGenerator_has_methods
    assert callable(test_Analysis_test_generator_JSTSTestGenerator_has_methods)

def test__generated_tests_tests_test_xray_Analysis_test_generator_test_Analysis_test_generator_TestGeneratorEngine_is_class_is_callable():
    """Verify test_Analysis_test_generator_TestGeneratorEngine_is_class exists and is callable."""
    from _generated_tests.tests.test_xray_Analysis_test_generator import test_Analysis_test_generator_TestGeneratorEngine_is_class
    assert callable(test_Analysis_test_generator_TestGeneratorEngine_is_class)

def test__generated_tests_tests_test_xray_Analysis_test_generator_test_Analysis_test_generator_TestGeneratorEngine_has_methods_is_callable():
    """Verify test_Analysis_test_generator_TestGeneratorEngine_has_methods exists and is callable."""
    from _generated_tests.tests.test_xray_Analysis_test_generator import test_Analysis_test_generator_TestGeneratorEngine_has_methods
    assert callable(test_Analysis_test_generator_TestGeneratorEngine_has_methods)
