"""Auto-generated monkey tests for _generated_tests/tests/test_xray_tests_test_phase1_modularization.py by X-Ray v7.0.

Tests function signatures, edge cases, and class instantiation.
"""


def test__generated_tests_tests_test_xray_tests_test_phase1_modularization_test_tests_test_phase1_modularization_test_extract_functions_is_callable_is_callable():
    """Verify test_tests_test_phase1_modularization_test_extract_functions_is_callable exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_phase1_modularization import test_tests_test_phase1_modularization_test_extract_functions_is_callable
    assert callable(test_tests_test_phase1_modularization_test_extract_functions_is_callable)

def test__generated_tests_tests_test_xray_tests_test_phase1_modularization_test_tests_test_phase1_modularization_test_ast_normalizer_is_callable_is_callable():
    """Verify test_tests_test_phase1_modularization_test_ast_normalizer_is_callable exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_phase1_modularization import test_tests_test_phase1_modularization_test_ast_normalizer_is_callable
    assert callable(test_tests_test_phase1_modularization_test_ast_normalizer_is_callable)

def test__generated_tests_tests_test_xray_tests_test_phase1_modularization_test_tests_test_phase1_modularization_test_tokenization_is_callable_is_callable():
    """Verify test_tests_test_phase1_modularization_test_tokenization_is_callable exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_phase1_modularization import test_tests_test_phase1_modularization_test_tokenization_is_callable
    assert callable(test_tests_test_phase1_modularization_test_tokenization_is_callable)

def test__generated_tests_tests_test_xray_tests_test_phase1_modularization_test_tests_test_phase1_modularization_test_code_similarity_exact_is_callable_is_callable():
    """Verify test_tests_test_phase1_modularization_test_code_similarity_exact_is_callable exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_phase1_modularization import test_tests_test_phase1_modularization_test_code_similarity_exact_is_callable
    assert callable(test_tests_test_phase1_modularization_test_code_similarity_exact_is_callable)

def test__generated_tests_tests_test_xray_tests_test_phase1_modularization_test_tests_test_phase1_modularization_test_code_similarity_diff_is_callable_is_callable():
    """Verify test_tests_test_phase1_modularization_test_code_similarity_diff_is_callable exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_phase1_modularization import test_tests_test_phase1_modularization_test_code_similarity_diff_is_callable
    assert callable(test_tests_test_phase1_modularization_test_code_similarity_diff_is_callable)

def test__generated_tests_tests_test_xray_tests_test_phase1_modularization_test_tests_test_phase1_modularization_test_semantic_similarity_is_callable_is_callable():
    """Verify test_tests_test_phase1_modularization_test_semantic_similarity_is_callable exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_phase1_modularization import test_tests_test_phase1_modularization_test_semantic_similarity_is_callable
    assert callable(test_tests_test_phase1_modularization_test_semantic_similarity_is_callable)

def test__generated_tests_tests_test_xray_tests_test_phase1_modularization_test_tests_test_phase1_modularization_test_duplicate_finder_exact_is_callable_is_callable():
    """Verify test_tests_test_phase1_modularization_test_duplicate_finder_exact_is_callable exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_phase1_modularization import test_tests_test_phase1_modularization_test_duplicate_finder_exact_is_callable
    assert callable(test_tests_test_phase1_modularization_test_duplicate_finder_exact_is_callable)

def test__generated_tests_tests_test_xray_tests_test_phase1_modularization_test_tests_test_phase1_modularization_test_smell_detection_is_callable_is_callable():
    """Verify test_tests_test_phase1_modularization_test_smell_detection_is_callable exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_phase1_modularization import test_tests_test_phase1_modularization_test_smell_detection_is_callable
    assert callable(test_tests_test_phase1_modularization_test_smell_detection_is_callable)
