"""Auto-generated monkey tests for _generated_tests/tests/test_xray_tests_test_analysis_tracer.py by X-Ray v7.0.

Tests function signatures, edge cases, and class instantiation.
"""


def test__generated_tests_tests_test_xray_tests_test_analysis_tracer_test_tests_test_analysis_tracer_test_type_tag_int_is_callable_is_callable():
    """Verify test_tests_test_analysis_tracer_test_type_tag_int_is_callable exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_analysis_tracer import test_tests_test_analysis_tracer_test_type_tag_int_is_callable
    assert callable(test_tests_test_analysis_tracer_test_type_tag_int_is_callable)

def test__generated_tests_tests_test_xray_tests_test_analysis_tracer_test_tests_test_analysis_tracer_test_type_tag_str_is_callable_is_callable():
    """Verify test_tests_test_analysis_tracer_test_type_tag_str_is_callable exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_analysis_tracer import test_tests_test_analysis_tracer_test_type_tag_str_is_callable
    assert callable(test_tests_test_analysis_tracer_test_type_tag_str_is_callable)

def test__generated_tests_tests_test_xray_tests_test_analysis_tracer_test_tests_test_analysis_tracer_test_type_tag_none_is_callable_is_callable():
    """Verify test_tests_test_analysis_tracer_test_type_tag_none_is_callable exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_analysis_tracer import test_tests_test_analysis_tracer_test_type_tag_none_is_callable
    assert callable(test_tests_test_analysis_tracer_test_type_tag_none_is_callable)

def test__generated_tests_tests_test_xray_tests_test_analysis_tracer_test_tests_test_analysis_tracer_test_type_tag_list_is_callable_is_callable():
    """Verify test_tests_test_analysis_tracer_test_type_tag_list_is_callable exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_analysis_tracer import test_tests_test_analysis_tracer_test_type_tag_list_is_callable
    assert callable(test_tests_test_analysis_tracer_test_type_tag_list_is_callable)

def test__generated_tests_tests_test_xray_tests_test_analysis_tracer_test_tests_test_analysis_tracer_test_type_tag_dict_is_callable_is_callable():
    """Verify test_tests_test_analysis_tracer_test_type_tag_dict_is_callable exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_analysis_tracer import test_tests_test_analysis_tracer_test_type_tag_dict_is_callable
    assert callable(test_tests_test_analysis_tracer_test_type_tag_dict_is_callable)

def test__generated_tests_tests_test_xray_tests_test_analysis_tracer_test_tests_test_analysis_tracer_test_safe_repr_normal_is_callable_is_callable():
    """Verify test_tests_test_analysis_tracer_test_safe_repr_normal_is_callable exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_analysis_tracer import test_tests_test_analysis_tracer_test_safe_repr_normal_is_callable
    assert callable(test_tests_test_analysis_tracer_test_safe_repr_normal_is_callable)

def test__generated_tests_tests_test_xray_tests_test_analysis_tracer_test_tests_test_analysis_tracer_test_safe_repr_string_is_callable_is_callable():
    """Verify test_tests_test_analysis_tracer_test_safe_repr_string_is_callable exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_analysis_tracer import test_tests_test_analysis_tracer_test_safe_repr_string_is_callable
    assert callable(test_tests_test_analysis_tracer_test_safe_repr_string_is_callable)

def test__generated_tests_tests_test_xray_tests_test_analysis_tracer_test_tests_test_analysis_tracer_test_safe_repr_truncation_is_callable_is_callable():
    """Verify test_tests_test_analysis_tracer_test_safe_repr_truncation_is_callable exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_analysis_tracer import test_tests_test_analysis_tracer_test_safe_repr_truncation_is_callable
    assert callable(test_tests_test_analysis_tracer_test_safe_repr_truncation_is_callable)

def test__generated_tests_tests_test_xray_tests_test_analysis_tracer_test_tests_test_analysis_tracer_test_wrap_preserves_return_is_callable_is_callable():
    """Verify test_tests_test_analysis_tracer_test_wrap_preserves_return_is_callable exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_analysis_tracer import test_tests_test_analysis_tracer_test_wrap_preserves_return_is_callable
    assert callable(test_tests_test_analysis_tracer_test_wrap_preserves_return_is_callable)

def test__generated_tests_tests_test_xray_tests_test_analysis_tracer_test_tests_test_analysis_tracer_test_wrap_preserves_name_is_callable_is_callable():
    """Verify test_tests_test_analysis_tracer_test_wrap_preserves_name_is_callable exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_analysis_tracer import test_tests_test_analysis_tracer_test_wrap_preserves_name_is_callable
    assert callable(test_tests_test_analysis_tracer_test_wrap_preserves_name_is_callable)

def test__generated_tests_tests_test_xray_tests_test_analysis_tracer_test_tests_test_analysis_tracer_test_wrap_captures_call_count_is_callable_is_callable():
    """Verify test_tests_test_analysis_tracer_test_wrap_captures_call_count_is_callable exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_analysis_tracer import test_tests_test_analysis_tracer_test_wrap_captures_call_count_is_callable
    assert callable(test_tests_test_analysis_tracer_test_wrap_captures_call_count_is_callable)

def test__generated_tests_tests_test_xray_tests_test_analysis_tracer_test_tests_test_analysis_tracer_test_wrap_captures_arg_types_is_callable_is_callable():
    """Verify test_tests_test_analysis_tracer_test_wrap_captures_arg_types_is_callable exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_analysis_tracer import test_tests_test_analysis_tracer_test_wrap_captures_arg_types_is_callable
    assert callable(test_tests_test_analysis_tracer_test_wrap_captures_arg_types_is_callable)

def test__generated_tests_tests_test_xray_tests_test_analysis_tracer_test_tests_test_analysis_tracer_test_wrap_captures_return_types_is_callable_is_callable():
    """Verify test_tests_test_analysis_tracer_test_wrap_captures_return_types_is_callable exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_analysis_tracer import test_tests_test_analysis_tracer_test_wrap_captures_return_types_is_callable
    assert callable(test_tests_test_analysis_tracer_test_wrap_captures_return_types_is_callable)

def test__generated_tests_tests_test_xray_tests_test_analysis_tracer_test_tests_test_analysis_tracer_test_wrap_captures_kwargs_is_callable_is_callable():
    """Verify test_tests_test_analysis_tracer_test_wrap_captures_kwargs_is_callable exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_analysis_tracer import test_tests_test_analysis_tracer_test_wrap_captures_kwargs_is_callable
    assert callable(test_tests_test_analysis_tracer_test_wrap_captures_kwargs_is_callable)

def test__generated_tests_tests_test_xray_tests_test_analysis_tracer_test_tests_test_analysis_tracer_test_wrap_captures_samples_is_callable_is_callable():
    """Verify test_tests_test_analysis_tracer_test_wrap_captures_samples_is_callable exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_analysis_tracer import test_tests_test_analysis_tracer_test_wrap_captures_samples_is_callable
    assert callable(test_tests_test_analysis_tracer_test_wrap_captures_samples_is_callable)

def test__generated_tests_tests_test_xray_tests_test_analysis_tracer_test_tests_test_analysis_tracer_test_wrap_records_timing_is_callable_is_callable():
    """Verify test_tests_test_analysis_tracer_test_wrap_records_timing_is_callable exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_analysis_tracer import test_tests_test_analysis_tracer_test_wrap_records_timing_is_callable
    assert callable(test_tests_test_analysis_tracer_test_wrap_records_timing_is_callable)

def test__generated_tests_tests_test_xray_tests_test_analysis_tracer_test_tests_test_analysis_tracer_test_exception_propagated_is_callable_is_callable():
    """Verify test_tests_test_analysis_tracer_test_exception_propagated_is_callable exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_analysis_tracer import test_tests_test_analysis_tracer_test_exception_propagated_is_callable
    assert callable(test_tests_test_analysis_tracer_test_exception_propagated_is_callable)

def test__generated_tests_tests_test_xray_tests_test_analysis_tracer_test_tests_test_analysis_tracer_test_exception_recorded_is_callable_is_callable():
    """Verify test_tests_test_analysis_tracer_test_exception_recorded_is_callable exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_analysis_tracer import test_tests_test_analysis_tracer_test_exception_recorded_is_callable
    assert callable(test_tests_test_analysis_tracer_test_exception_recorded_is_callable)

def test__generated_tests_tests_test_xray_tests_test_analysis_tracer_test_tests_test_analysis_tracer_test_exception_marks_impure_is_callable_is_callable():
    """Verify test_tests_test_analysis_tracer_test_exception_marks_impure_is_callable exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_analysis_tracer import test_tests_test_analysis_tracer_test_exception_marks_impure_is_callable
    assert callable(test_tests_test_analysis_tracer_test_exception_marks_impure_is_callable)

def test__generated_tests_tests_test_xray_tests_test_analysis_tracer_test_tests_test_analysis_tracer_test_exception_sample_has_error_is_callable_is_callable():
    """Verify test_tests_test_analysis_tracer_test_exception_sample_has_error_is_callable exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_analysis_tracer import test_tests_test_analysis_tracer_test_exception_sample_has_error_is_callable
    assert callable(test_tests_test_analysis_tracer_test_exception_sample_has_error_is_callable)

def test__generated_tests_tests_test_xray_tests_test_analysis_tracer_test_tests_test_analysis_tracer_test_mixed_success_and_error_is_callable_is_callable():
    """Verify test_tests_test_analysis_tracer_test_mixed_success_and_error_is_callable exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_analysis_tracer import test_tests_test_analysis_tracer_test_mixed_success_and_error_is_callable
    assert callable(test_tests_test_analysis_tracer_test_mixed_success_and_error_is_callable)

def test__generated_tests_tests_test_xray_tests_test_analysis_tracer_test_tests_test_analysis_tracer_test_samples_capped_is_callable_is_callable():
    """Verify test_tests_test_analysis_tracer_test_samples_capped_is_callable exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_analysis_tracer import test_tests_test_analysis_tracer_test_samples_capped_is_callable
    assert callable(test_tests_test_analysis_tracer_test_samples_capped_is_callable)

def test__generated_tests_tests_test_xray_tests_test_analysis_tracer_test_tests_test_analysis_tracer_test_lookup_by_name_is_callable_is_callable():
    """Verify test_tests_test_analysis_tracer_test_lookup_by_name_is_callable exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_analysis_tracer import test_tests_test_analysis_tracer_test_lookup_by_name_is_callable
    assert callable(test_tests_test_analysis_tracer_test_lookup_by_name_is_callable)

def test__generated_tests_tests_test_xray_tests_test_analysis_tracer_test_tests_test_analysis_tracer_test_lookup_missing_is_callable_is_callable():
    """Verify test_tests_test_analysis_tracer_test_lookup_missing_is_callable exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_analysis_tracer import test_tests_test_analysis_tracer_test_lookup_missing_is_callable
    assert callable(test_tests_test_analysis_tracer_test_lookup_missing_is_callable)

def test__generated_tests_tests_test_xray_tests_test_analysis_tracer_test_tests_test_analysis_tracer_test_noop_returns_none_is_callable_is_callable():
    """Verify test_tests_test_analysis_tracer_test_noop_returns_none_is_callable exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_analysis_tracer import test_tests_test_analysis_tracer_test_noop_returns_none_is_callable
    assert callable(test_tests_test_analysis_tracer_test_noop_returns_none_is_callable)

def test__generated_tests_tests_test_xray_tests_test_analysis_tracer_test_tests_test_analysis_tracer_test_noop_captures_none_type_is_callable_is_callable():
    """Verify test_tests_test_analysis_tracer_test_noop_captures_none_type_is_callable exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_analysis_tracer import test_tests_test_analysis_tracer_test_noop_captures_none_type_is_callable
    assert callable(test_tests_test_analysis_tracer_test_noop_captures_none_type_is_callable)

def test__generated_tests_tests_test_xray_tests_test_analysis_tracer_test_tests_test_analysis_tracer_test_save_load_roundtrip_is_callable_is_callable():
    """Verify test_tests_test_analysis_tracer_test_save_load_roundtrip_is_callable exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_analysis_tracer import test_tests_test_analysis_tracer_test_save_load_roundtrip_is_callable
    assert callable(test_tests_test_analysis_tracer_test_save_load_roundtrip_is_callable)

def test__generated_tests_tests_test_xray_tests_test_analysis_tracer_test_tests_test_analysis_tracer_test_save_load_roundtrip_none_args_is_callable():
    """Verify test_tests_test_analysis_tracer_test_save_load_roundtrip_none_args exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_analysis_tracer import test_tests_test_analysis_tracer_test_save_load_roundtrip_none_args
    assert callable(test_tests_test_analysis_tracer_test_save_load_roundtrip_none_args)

def test__generated_tests_tests_test_xray_tests_test_analysis_tracer_test_tests_test_analysis_tracer_test_save_creates_valid_json_is_callable_is_callable():
    """Verify test_tests_test_analysis_tracer_test_save_creates_valid_json_is_callable exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_analysis_tracer import test_tests_test_analysis_tracer_test_save_creates_valid_json_is_callable
    assert callable(test_tests_test_analysis_tracer_test_save_creates_valid_json_is_callable)

def test__generated_tests_tests_test_xray_tests_test_analysis_tracer_test_tests_test_analysis_tracer_test_save_creates_valid_json_none_args_is_callable():
    """Verify test_tests_test_analysis_tracer_test_save_creates_valid_json_none_args exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_analysis_tracer import test_tests_test_analysis_tracer_test_save_creates_valid_json_none_args
    assert callable(test_tests_test_analysis_tracer_test_save_creates_valid_json_none_args)

def test__generated_tests_tests_test_xray_tests_test_analysis_tracer_test_tests_test_analysis_tracer_test_avg_time_us_is_callable_is_callable():
    """Verify test_tests_test_analysis_tracer_test_avg_time_us_is_callable exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_analysis_tracer import test_tests_test_analysis_tracer_test_avg_time_us_is_callable
    assert callable(test_tests_test_analysis_tracer_test_avg_time_us_is_callable)

def test__generated_tests_tests_test_xray_tests_test_analysis_tracer_test_tests_test_analysis_tracer_test_avg_time_us_zero_calls_is_callable_is_callable():
    """Verify test_tests_test_analysis_tracer_test_avg_time_us_zero_calls_is_callable exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_analysis_tracer import test_tests_test_analysis_tracer_test_avg_time_us_zero_calls_is_callable
    assert callable(test_tests_test_analysis_tracer_test_avg_time_us_zero_calls_is_callable)

def test__generated_tests_tests_test_xray_tests_test_analysis_tracer_test_tests_test_analysis_tracer_test_dominant_return_type_is_callable_is_callable():
    """Verify test_tests_test_analysis_tracer_test_dominant_return_type_is_callable exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_analysis_tracer import test_tests_test_analysis_tracer_test_dominant_return_type_is_callable
    assert callable(test_tests_test_analysis_tracer_test_dominant_return_type_is_callable)

def test__generated_tests_tests_test_xray_tests_test_analysis_tracer_test_tests_test_analysis_tracer_test_dominant_return_type_empty_is_callable_is_callable():
    """Verify test_tests_test_analysis_tracer_test_dominant_return_type_empty_is_callable exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_analysis_tracer import test_tests_test_analysis_tracer_test_dominant_return_type_empty_is_callable
    assert callable(test_tests_test_analysis_tracer_test_dominant_return_type_empty_is_callable)

def test__generated_tests_tests_test_xray_tests_test_analysis_tracer_test_tests_test_analysis_tracer_test_to_dict_is_callable_is_callable():
    """Verify test_tests_test_analysis_tracer_test_to_dict_is_callable exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_analysis_tracer import test_tests_test_analysis_tracer_test_to_dict_is_callable
    assert callable(test_tests_test_analysis_tracer_test_to_dict_is_callable)

def test__generated_tests_tests_test_xray_tests_test_analysis_tracer_test_tests_test_analysis_tracer_test_reset_clears_profiles_is_callable_is_callable():
    """Verify test_tests_test_analysis_tracer_test_reset_clears_profiles_is_callable exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_analysis_tracer import test_tests_test_analysis_tracer_test_reset_clears_profiles_is_callable
    assert callable(test_tests_test_analysis_tracer_test_reset_clears_profiles_is_callable)

def test__generated_tests_tests_test_xray_tests_test_analysis_tracer_test_tests_test_analysis_tracer_TestTypeTagAndRepr_is_class_is_callable():
    """Verify test_tests_test_analysis_tracer_TestTypeTagAndRepr_is_class exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_analysis_tracer import test_tests_test_analysis_tracer_TestTypeTagAndRepr_is_class
    assert callable(test_tests_test_analysis_tracer_TestTypeTagAndRepr_is_class)

def test__generated_tests_tests_test_xray_tests_test_analysis_tracer_test_tests_test_analysis_tracer_TestTypeTagAndRepr_has_methods_is_callable():
    """Verify test_tests_test_analysis_tracer_TestTypeTagAndRepr_has_methods exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_analysis_tracer import test_tests_test_analysis_tracer_TestTypeTagAndRepr_has_methods
    assert callable(test_tests_test_analysis_tracer_TestTypeTagAndRepr_has_methods)

def test__generated_tests_tests_test_xray_tests_test_analysis_tracer_test_tests_test_analysis_tracer_TestTracerWrap_is_class_is_callable():
    """Verify test_tests_test_analysis_tracer_TestTracerWrap_is_class exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_analysis_tracer import test_tests_test_analysis_tracer_TestTracerWrap_is_class
    assert callable(test_tests_test_analysis_tracer_TestTracerWrap_is_class)

def test__generated_tests_tests_test_xray_tests_test_analysis_tracer_test_tests_test_analysis_tracer_TestTracerWrap_has_methods_is_callable():
    """Verify test_tests_test_analysis_tracer_TestTracerWrap_has_methods exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_analysis_tracer import test_tests_test_analysis_tracer_TestTracerWrap_has_methods
    assert callable(test_tests_test_analysis_tracer_TestTracerWrap_has_methods)

def test__generated_tests_tests_test_xray_tests_test_analysis_tracer_test_tests_test_analysis_tracer_TestTracerExceptions_is_class_is_callable():
    """Verify test_tests_test_analysis_tracer_TestTracerExceptions_is_class exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_analysis_tracer import test_tests_test_analysis_tracer_TestTracerExceptions_is_class
    assert callable(test_tests_test_analysis_tracer_TestTracerExceptions_is_class)

def test__generated_tests_tests_test_xray_tests_test_analysis_tracer_test_tests_test_analysis_tracer_TestTracerExceptions_has_methods_is_callable():
    """Verify test_tests_test_analysis_tracer_TestTracerExceptions_has_methods exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_analysis_tracer import test_tests_test_analysis_tracer_TestTracerExceptions_has_methods
    assert callable(test_tests_test_analysis_tracer_TestTracerExceptions_has_methods)

def test__generated_tests_tests_test_xray_tests_test_analysis_tracer_test_tests_test_analysis_tracer_TestTracerSampleCap_is_class_is_callable():
    """Verify test_tests_test_analysis_tracer_TestTracerSampleCap_is_class exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_analysis_tracer import test_tests_test_analysis_tracer_TestTracerSampleCap_is_class
    assert callable(test_tests_test_analysis_tracer_TestTracerSampleCap_is_class)

def test__generated_tests_tests_test_xray_tests_test_analysis_tracer_test_tests_test_analysis_tracer_TestTracerSampleCap_has_methods_is_callable():
    """Verify test_tests_test_analysis_tracer_TestTracerSampleCap_has_methods exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_analysis_tracer import test_tests_test_analysis_tracer_TestTracerSampleCap_has_methods
    assert callable(test_tests_test_analysis_tracer_TestTracerSampleCap_has_methods)

def test__generated_tests_tests_test_xray_tests_test_analysis_tracer_test_tests_test_analysis_tracer_TestProfileFor_is_class_is_callable():
    """Verify test_tests_test_analysis_tracer_TestProfileFor_is_class exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_analysis_tracer import test_tests_test_analysis_tracer_TestProfileFor_is_class
    assert callable(test_tests_test_analysis_tracer_TestProfileFor_is_class)

def test__generated_tests_tests_test_xray_tests_test_analysis_tracer_test_tests_test_analysis_tracer_TestProfileFor_has_methods_is_callable():
    """Verify test_tests_test_analysis_tracer_TestProfileFor_has_methods exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_analysis_tracer import test_tests_test_analysis_tracer_TestProfileFor_has_methods
    assert callable(test_tests_test_analysis_tracer_TestProfileFor_has_methods)

def test__generated_tests_tests_test_xray_tests_test_analysis_tracer_test_tests_test_analysis_tracer_TestTracerNoop_is_class_is_callable():
    """Verify test_tests_test_analysis_tracer_TestTracerNoop_is_class exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_analysis_tracer import test_tests_test_analysis_tracer_TestTracerNoop_is_class
    assert callable(test_tests_test_analysis_tracer_TestTracerNoop_is_class)

def test__generated_tests_tests_test_xray_tests_test_analysis_tracer_test_tests_test_analysis_tracer_TestTracerNoop_has_methods_is_callable():
    """Verify test_tests_test_analysis_tracer_TestTracerNoop_has_methods exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_analysis_tracer import test_tests_test_analysis_tracer_TestTracerNoop_has_methods
    assert callable(test_tests_test_analysis_tracer_TestTracerNoop_has_methods)

def test__generated_tests_tests_test_xray_tests_test_analysis_tracer_test_tests_test_analysis_tracer_TestTracerSerialisation_is_class_is_callable():
    """Verify test_tests_test_analysis_tracer_TestTracerSerialisation_is_class exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_analysis_tracer import test_tests_test_analysis_tracer_TestTracerSerialisation_is_class
    assert callable(test_tests_test_analysis_tracer_TestTracerSerialisation_is_class)

def test__generated_tests_tests_test_xray_tests_test_analysis_tracer_test_tests_test_analysis_tracer_TestTracerSerialisation_has_methods_is_callable():
    """Verify test_tests_test_analysis_tracer_TestTracerSerialisation_has_methods exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_analysis_tracer import test_tests_test_analysis_tracer_TestTracerSerialisation_has_methods
    assert callable(test_tests_test_analysis_tracer_TestTracerSerialisation_has_methods)

def test__generated_tests_tests_test_xray_tests_test_analysis_tracer_test_tests_test_analysis_tracer_TestTraceProfileProperties_is_class_is_callable():
    """Verify test_tests_test_analysis_tracer_TestTraceProfileProperties_is_class exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_analysis_tracer import test_tests_test_analysis_tracer_TestTraceProfileProperties_is_class
    assert callable(test_tests_test_analysis_tracer_TestTraceProfileProperties_is_class)

def test__generated_tests_tests_test_xray_tests_test_analysis_tracer_test_tests_test_analysis_tracer_TestTraceProfileProperties_has_methods_is_callable():
    """Verify test_tests_test_analysis_tracer_TestTraceProfileProperties_has_methods exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_analysis_tracer import test_tests_test_analysis_tracer_TestTraceProfileProperties_has_methods
    assert callable(test_tests_test_analysis_tracer_TestTraceProfileProperties_has_methods)

def test__generated_tests_tests_test_xray_tests_test_analysis_tracer_test_tests_test_analysis_tracer_TestTracerReset_is_class_is_callable():
    """Verify test_tests_test_analysis_tracer_TestTracerReset_is_class exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_analysis_tracer import test_tests_test_analysis_tracer_TestTracerReset_is_class
    assert callable(test_tests_test_analysis_tracer_TestTracerReset_is_class)

def test__generated_tests_tests_test_xray_tests_test_analysis_tracer_test_tests_test_analysis_tracer_TestTracerReset_has_methods_is_callable():
    """Verify test_tests_test_analysis_tracer_TestTracerReset_has_methods exists and is callable."""
    from _generated_tests.tests.test_xray_tests_test_analysis_tracer import test_tests_test_analysis_tracer_TestTracerReset_has_methods
    assert callable(test_tests_test_analysis_tracer_TestTracerReset_has_methods)
