"""
JavaScript / TypeScript rules — deep analysis for frontend code.
Covers: security, React patterns, dead imports, event handling, async safety.
"""

# ── Security Rules (JS-specific) ──────────────────────────────────────

JS_SEC_RULES = [
    {
        "id": "JS-SEC-001",
        "severity": "HIGH",
        "lang": ["javascript", "html"],
        "pattern": r"\.innerHTML\s*=\s*(?!.*(?:escHtml|escapeHtml|sanitize|DOMPurify|textContent))",
        "description": "Insecure innerHTML assignment — XSS risk without sanitization",
        "fix_hint": "Use textContent for plain text or DOMPurify.sanitize() for HTML",
        "test_hint": "Verify all innerHTML assignments are sanitized",
        "cwe": "CWE-79",
        "owasp": "A03:2021-Injection",
    },
    {
        "id": "JS-SEC-002",
        "severity": "HIGH",
        "lang": ["javascript", "html"],
        "pattern": r"document\.write\s*\(",
        "description": "document.write() usage — XSS risk and blocks page rendering",
        "fix_hint": "Use DOM manipulation methods (createElement, appendChild) instead",
        "test_hint": "Verify document.write is not used anywhere in production code",
        "cwe": "CWE-79",
        "owasp": "A03:2021-Injection",
    },
    {
        "id": "JS-SEC-003",
        "severity": "HIGH",
        "lang": ["javascript", "html"],
        "pattern": r"\beval\s*\(",
        "description": "eval() usage — code injection risk",
        "fix_hint": "Use JSON.parse() for data or Function constructor with validation",
        "test_hint": "Verify eval is not used with user-controlled input",
        "cwe": "CWE-95",
        "owasp": "A03:2021-Injection",
    },
    {
        "id": "JS-SEC-004",
        "severity": "HIGH",
        "lang": ["javascript", "html"],
        "pattern": r"(?:localStorage|sessionStorage)\s*\.\s*setItem\s*\(\s*['\"](?:token|secret|password|api[_-]?key|auth|jwt|session)",
        "description": "Storing secrets in localStorage/sessionStorage — accessible to XSS attacks",
        "fix_hint": "Use httpOnly cookies for auth tokens, or encrypt before storing",
        "test_hint": "Verify sensitive data is not stored in browser storage",
        "cwe": "CWE-922",
        "owasp": "A02:2021-Cryptographic-Failures",
    },
    {
        "id": "JS-SEC-005",
        "severity": "MEDIUM",
        "lang": ["javascript"],
        "pattern": r"(?:window\.)?postMessage\s*\([^)]*,[^)]*['\"\s]*\*['\"\s]*\)",
        "description": "postMessage with wildcard origin — any page can receive the message",
        "fix_hint": "Specify exact target origin instead of '*'",
        "test_hint": "Verify postMessage uses specific origin, not wildcard",
        "cwe": "CWE-346",
        "owasp": "A01:2021-Broken-Access-Control",
    },
    {
        "id": "JS-SEC-006",
        "severity": "HIGH",
        "lang": ["javascript"],
        "pattern": r"new\s+Function\s*\(",
        "description": "Dynamic Function constructor — similar to eval(), code injection risk",
        "fix_hint": "Avoid dynamic code generation; use static functions or safe alternatives",
        "test_hint": "Verify Function constructor is not used with user input",
        "cwe": "CWE-95",
        "owasp": "A03:2021-Injection",
    },
    {
        "id": "JS-SEC-007",
        "severity": "MEDIUM",
        "lang": ["javascript", "html"],
        "pattern": r"<form\b[^>]*(?!.*csrf|.*_token|.*xsrf)[^>]*>",
        "description": "Form without CSRF token — vulnerable to cross-site request forgery",
        "fix_hint": "Include a CSRF token hidden field in every form",
        "test_hint": "Verify all forms include CSRF protection tokens",
        "cwe": "CWE-352",
        "owasp": "A01:2021-Broken-Access-Control",
    },
    {
        "id": "JS-SEC-008",
        "severity": "HIGH",
        "lang": ["javascript"],
        "pattern": r"\b(?:Object\.assign|_\.merge|_\.extend|_\.defaultsDeep)\s*\(\s*(?:req\.body|req\.query|req\.params|user[Ii]nput|data)",
        "description": "Prototype pollution risk — merging untrusted data into objects",
        "fix_hint": "Validate input keys, use Object.create(null) or structured cloning",
        "test_hint": "Verify object merges don't accept __proto__ or constructor keys",
        "cwe": "CWE-1321",
        "owasp": "A03:2021-Injection",
    },
]

# ── React / Component Rules ──────────────────────────────────────────

JS_REACT_RULES = [
    {
        "id": "JS-REACT-001",
        "severity": "MEDIUM",
        "lang": ["javascript"],
        "pattern": r"dangerouslySetInnerHTML\s*=\s*\{",
        "description": "dangerouslySetInnerHTML usage — explicit XSS bypass in React",
        "fix_hint": "Use DOMPurify.sanitize() on the HTML string before rendering",
        "test_hint": "Verify dangerouslySetInnerHTML content is sanitized",
        "cwe": "CWE-79",
        "owasp": "A03:2021-Injection",
    },
    {
        "id": "JS-REACT-002",
        "severity": "MEDIUM",
        "lang": ["javascript"],
        "pattern": r"useEffect\s*\(\s*(?:async\s+)?\(\s*\)\s*=>\s*\{[^}]*(?:fetch|axios|api\(|\.get\(|\.post\()[^}]*\}\s*,\s*\[\s*\]\s*\)",
        "description": "useEffect with empty deps fetching data — missing cleanup/abort controller",
        "fix_hint": "Add AbortController cleanup to prevent state updates on unmounted component",
        "test_hint": "Verify async effects handle component unmounting",
        "cwe": "CWE-404",
        "owasp": "",
    },
    {
        "id": "JS-REACT-003",
        "severity": "LOW",
        "lang": ["javascript"],
        "pattern": r"useState\s*\(\s*\[\s*\]\s*\)|useState\s*\(\s*\{\s*\}\s*\)",
        "description": "useState with new object/array reference — may cause unnecessary re-renders",
        "fix_hint": "Define default values outside the component or use useMemo",
        "test_hint": "Verify initial state values are stable references",
        "cwe": "",
        "owasp": "",
    },
    {
        "id": "JS-REACT-004",
        "severity": "MEDIUM",
        "lang": ["javascript"],
        "pattern": r"(?:setState|dispatch)\s*\(\s*(?:.*\bstate\b)",
        "description": "State update referencing stale state — use functional updater",
        "fix_hint": "Use setState(prev => ...) functional form to avoid stale closure",
        "test_hint": "Verify state updates use functional form when referencing current state",
        "cwe": "CWE-362",
        "owasp": "",
    },
]

# ── Quality / Best Practice Rules ─────────────────────────────────────

JS_QUALITY_RULES = [
    {
        "id": "JS-QUAL-001",
        "severity": "MEDIUM",
        "lang": ["javascript"],
        "pattern": r"\.catch\s*\(\s*\(\s*\)\s*=>\s*\{\s*\}\s*\)",
        "description": "Empty .catch() handler — silently swallows errors",
        "fix_hint": "Log the error or handle it appropriately",
        "test_hint": "Verify promise rejections are properly handled",
        "cwe": "CWE-390",
        "owasp": "",
    },
    {
        "id": "JS-QUAL-002",
        "severity": "MEDIUM",
        "lang": ["javascript"],
        "pattern": r"(?:async\s+function|\basync\s*\([^)]*\)\s*=>)\s*\{(?:(?!try\s*\{|\.catch\s*\()[\s\S])*(?:await\s+)",
        "description": "Async function without try/catch — unhandled Promise rejection",
        "fix_hint": "Wrap await calls in try/catch or add .catch() to the Promise chain",
        "test_hint": "Verify async functions handle rejection scenarios",
        "cwe": "CWE-755",
        "owasp": "",
    },
    {
        "id": "JS-QUAL-003",
        "severity": "LOW",
        "lang": ["javascript"],
        "pattern": r"console\.\s*(?:log|warn|error|debug|info|trace)\s*\(",
        "description": "Console statement left in code — use a proper logging library",
        "fix_hint": "Remove console statements or replace with structured logging",
        "test_hint": "Verify production code uses logging library, not console.*",
        "cwe": "CWE-497",
        "owasp": "",
    },
    {
        "id": "JS-QUAL-004",
        "severity": "MEDIUM",
        "lang": ["javascript"],
        "pattern": r"(?:==\s*null|!=\s*null|==\s*undefined|!=\s*undefined)(?!\s*=)",
        "description": "Loose equality with null/undefined — use === or !== for type safety",
        "fix_hint": "Use === null, !== null, or optional chaining (?.) for null checks",
        "test_hint": "Verify null/undefined checks use strict equality",
        "cwe": "CWE-480",
        "owasp": "",
    },
    {
        "id": "JS-QUAL-005",
        "severity": "MEDIUM",
        "lang": ["javascript"],
        "pattern": r"(?:var\s+\w+)",
        "description": "var declaration — use let/const for block scoping",
        "fix_hint": "Replace var with const (preferred) or let",
        "test_hint": "Verify no var declarations remain in modern code",
        "cwe": "",
        "owasp": "",
    },
    {
        "id": "JS-QUAL-006",
        "severity": "LOW",
        "lang": ["javascript"],
        "pattern": r"(?://|/\*)\s*(?:TO" + r"DO|FIX" + r"ME|HA" + r"CK|XX" + r"X)\b",
        "description": "TO" + "DO/FIX" + "ME marker left in JavaScript code",
        "fix_hint": "Address the issue or create a tracking ticket",
        "test_hint": "Verify all markers have been resolved before release",
        "cwe": "CWE-546",
        "owasp": "",
    },
    {
        "id": "JS-QUAL-007",
        "severity": "MEDIUM",
        "lang": ["javascript"],
        "pattern": r"(?:setTimeout|setInterval)\s*\([^,)]+,\s*0\s*\)",
        "description": "setTimeout/setInterval with 0ms delay — often masks timing issues",
        "fix_hint": "Use requestAnimationFrame or proper event-driven patterns",
        "test_hint": "Verify zero-delay timers are intentional and documented",
        "cwe": "",
        "owasp": "",
    },
    {
        "id": "JS-QUAL-008",
        "severity": "HIGH",
        "lang": ["javascript"],
        "pattern": r"(?:catch\s*\(\s*\w+\s*\)\s*\{[^}]*(?:throw\s+\w+|throw\s+new\s+Error).*\})",
        "description": "Re-throwing caught error without wrapping — loses original stack trace",
        "fix_hint": "Use throw new Error('context', { cause: err }) to preserve the chain",
        "test_hint": "Verify re-thrown errors preserve the original cause",
        "cwe": "CWE-755",
        "owasp": "",
    },
]

# ── Dead Import / Unused Patterns ─────────────────────────────────────

JS_DEAD_CODE_RULES = [
    {
        "id": "JS-DEAD-001",
        "severity": "LOW",
        "lang": ["javascript"],
        "pattern": r"^import\s+\{[^}]+\}\s+from\s+['\"](?:react|react-dom)['\"];?\s*$",
        "description": "React import — verify all named imports are actually used in JSX",
        "fix_hint": "Remove unused React imports (React 17+ doesn't require React in scope)",
        "test_hint": "Verify imported React hooks/components are referenced in the file",
        "cwe": "",
        "owasp": "",
    },
]

# ── All JS/TS Rules ───────────────────────────────────────────────────

JAVASCRIPT_RULES = JS_SEC_RULES + JS_REACT_RULES + JS_QUALITY_RULES + JS_DEAD_CODE_RULES
