"""
Python-specific anti-pattern rules.
Sourced from real bugs found during X-Ray audits.
"""

PYTHON_RULES = [
    {
        "id": "PY-001",
        "severity": "MEDIUM",
        "lang": ["python"],
        "pattern": r"def\s+\w+\([^)]*\)\s*->\s*None:",
        "description": "Function annotated as -> None but returns a dict",
        "fix_hint": "Fix the return type annotation to match actual return value",
        "test_hint": "Verify function return types match their annotations",
    },
    {
        "id": "PY-002",
        "severity": "HIGH",
        "lang": ["python"],
        "pattern": r"self\.\w+\([^)]*\)\.items\(\)",
        "description": "Calling .items() on method that returns None (common in HTTP handlers)",
        "fix_hint": "Check if the method returns a dict or None before calling .items()",
        "test_hint": "Test that methods returning None are not iterated with .items()",
    },
    {
        "id": "PY-003",
        "severity": "MEDIUM",
        "lang": ["python"],
        "pattern": r"import\s+\*|from\s+\w+\s+import\s+\*",
        "description": "Wildcard import pollutes namespace and hides dependencies",
        "fix_hint": "Import specific names: from module import func1, func2",
        "test_hint": "Verify no wildcard imports exist in production code",
    },
    {
        "id": "PY-004",
        "severity": "LOW",
        "lang": ["python"],
        "pattern": r"pri" + r"nt\s*\(",
        "description": "Debug " + "print statement left in code — use logging instead",
        "fix_hint": "Replace pri" + "nt() with logging.debug/info/warning as appropriate",
        "test_hint": "Verify production code uses logging module instead of pri" + "nt()",
    },
    {
        "id": "PY-005",
        "severity": "HIGH",
        "lang": ["python"],
        "pattern": r"(json\.loads|json\.load)\([^)]+\)(?!\s*#\s*nosec)(?![^#]*(try|except))",
        "description": "JSON parsing without error handling — crashes on malformed input",
        "fix_hint": "Wrap json.loads() in try/except json.JSONDecodeError",
        "test_hint": "Test that malformed JSON input returns an error response, not a crash",
    },
    {
        "id": "PY-006",
        "severity": "MEDIUM",
        "lang": ["python"],
        "pattern": r"global\s+\w+",
        "description": "Glob" + "al variable mutation — hard to test and reason about",
        "fix_hint": "Pass state through function parameters or use a class",
        "test_hint": "Verify glob" + "al state is minimized and thread-safe if concurrent",
    },
    {
        "id": "PY-007",
        "severity": "MEDIUM",
        "lang": ["python"],
        "pattern": r"os\.environ\[",
        "description": "Direct os.envir" + "on[] access crashes on missing key — use .get() with default",
        "fix_hint": "Use os.envir" + "on.get('KEY', 'default') instead of os.envir" + "on['KEY']",
        "test_hint": "Verify environment variable access has defaults for missing keys",
    },
    {
        "id": "PY-008",
        "severity": "MEDIUM",
        "lang": ["python"],
        "pattern": r"\bopen\((?![^)]*(?:encoding|['\"]r?b['\"]))[^)]+\)",
        "description": "File opened without explicit encoding — platform-dependent behavior",
        "fix_hint": "Always specify encoding='utf-8' for text file operations",
        "test_hint": "Verify all text file opens specify explicit encoding",
    },
    {
        "id": "PY-009",
        "severity": "MEDIUM",
        "lang": ["python"],
        "pattern": r"except\s+\w+\s+as\s+\w+\s*:\s*\n\s*(pass|\.\.\.)\s*$",
        "description": "Exception captured into variable but silently ignored",
        "fix_hint": "Log the exception: logging.warning('...', exc_info=True) or re-raise",
        "test_hint": "Verify captured exceptions are logged, handled, or re-raised",
    },
    {
        "id": "PY-010",
        "severity": "MEDIUM",
        "lang": ["python"],
        "pattern": r"sys\.exit\(\d+\)",
        "description": "sys.exit() in library code — kills the entire process, prevents reuse",
        "fix_hint": "Raise an exception instead; let the caller decide how to handle failure",
        "test_hint": "Verify library functions raise exceptions instead of calling sys.exit()",
    },
    {
        "id": "PY-011",
        "severity": "LOW",
        "lang": ["python"],
        "pattern": r"isinstance\([^,]+,\s*\([^)]{80,}\)\)",
        "description": "isinstance with too many types — indicates missing polymorphism or protocol",
        "fix_hint": "Use Protocol, ABC, or structural dispatch instead of long isinstance chains",
        "test_hint": "Verify type checking uses protocols or ABC instead of long isinstance tuples",
    },
]
