"""
Security rules — XSS, injection, SSRF, auth failures.
Every rule sourced from real bugs found during X-Ray audits.
"""

SECURITY_RULES = [
    {
        "id": "SEC-001",
        "severity": "HIGH",
        "lang": ["javascript", "html"],
        "pattern": r"\.innerHTML\s*=\s*`[^`]*\$\{(?![^`]*(escHtml|escapeHtml|sanitize|DOMPurify|textContent))",
        "description": "XSS: Template literal injected into innerHTML without sanitization",
        "fix_hint": "Wrap all dynamic values with an HTML escape function or use textContent",
        "test_hint": "Verify _escHtml or equivalent sanitizer wraps all dynamic values in innerHTML assignments",
    },
    {
        "id": "SEC-002",
        "severity": "HIGH",
        "lang": ["javascript", "html"],
        "pattern": r"\.innerHTML\s*=\s*['\"][^'\"]*['\"]\s*\+\s*\w+",
        "description": "XSS: String concatenation with variable injected into innerHTML",
        "fix_hint": "Use textContent or sanitize the variable before injection",
        "test_hint": "Check that no unsanitized variables are concatenated into innerHTML",
    },
    {
        "id": "SEC-003",
        "severity": "HIGH",
        "lang": ["python"],
        "pattern": r"(subprocess\.(run|call|Popen|check_output)\([^)]*\b(shell\s*=\s*True))",
        "description": "Command injection: subprocess called with shell=True",
        "fix_hint": "Use shell=False and pass args as a list",
        "test_hint": "Verify subprocess calls do not use shell=True with user-controlled input",
    },
    {
        "id": "SEC-004",
        "severity": "HIGH",
        "lang": ["python"],
        "pattern": r"(execute|executemany)\(\s*(f['\"][^'\"]*\{[^}]*\}|['\"][^'\"]*%s)",
        "description": "SQL injection: String formatting in SQL query",
        "fix_hint": "Use parameterized queries with ? or %s placeholders",
        "test_hint": "Verify SQL queries use parameterized binding, not string formatting",
    },
    {
        "id": "SEC-005",
        "severity": "MEDIUM",
        "lang": ["python"],
        "pattern": r"urlopen\(.*\+|urlopen\(f['\"]|requests\.(get|post|put|delete)\(.*\+",
        "description": "SSRF: URL constructed from user input without validation",
        "fix_hint": "Validate URLs against an allowlist of trusted hosts before making requests",
        "test_hint": "Test that URL validation rejects internal/private IPs and non-allowlisted hosts",
    },
    {
        "id": "SEC-006",
        "severity": "MEDIUM",
        "lang": ["python"],
        "pattern": r"Access-Control-Allow-Origin['\"],?\s*['\"]?\*",
        "description": "CORS misconfiguration: wildcard origin allows any site",
        "fix_hint": "Restrict CORS to specific trusted origins (e.g., localhost)",
        "test_hint": "Verify CORS headers never return wildcard (*) for credentialed requests",
    },
    {
        "id": "SEC-007",
        "severity": "HIGH",
        "lang": ["python", "javascript"],
        "pattern": r"(eval|exec)\s*\(",
        "description": "Code injection: eval/exec with potentially untrusted input",
        "fix_hint": "Replace eval/exec with safe alternatives (ast.literal_eval, JSON.parse)",
        "test_hint": "Verify no eval/exec is used on user-controlled data",
    },
    {
        "id": "SEC-008",
        "severity": "MEDIUM",
        "lang": ["python"],
        "pattern": r"(password|secret|token|api_key)\s*=\s*['\"][^'\"]+['\"]",
        "description": "Hardcoded secret: credential embedded in source code",
        "fix_hint": "Move secrets to environment variables or a secrets manager",
        "test_hint": "Verify no hardcoded passwords/tokens/keys exist in source code",
    },
    {
        "id": "SEC-009",
        "severity": "HIGH",
        "lang": ["python"],
        "pattern": r"pickle\.loads?\(|yaml\.load\([^)]*(?!Loader\s*=\s*yaml\.SafeLoader)",
        "description": "Deserialization attack: unsafe pickle/yaml loading",
        "fix_hint": "Use json or yaml.safe_load instead of pickle.loads/yaml.load",
        "test_hint": "Verify no unsafe deserialization is used on untrusted data",
    },
    {
        "id": "SEC-010",
        "severity": "MEDIUM",
        "lang": ["python"],
        "pattern": r"os\.path\.join\(.*\.\.\s*/",
        "description": "Path traversal: user input may escape intended directory",
        "fix_hint": "Validate and normalize paths, reject '..' components",
        "test_hint": "Verify path inputs are sanitized against directory traversal",
    },
    {
        "id": "SEC-011",
        "severity": "MEDIUM",
        "lang": ["python"],
        "pattern": r"(password|secret|token|api_key|hash|digest)\s*==\s*",
        "description": "Timing attack: comparing secrets with == instead of constant-time compare",
        "fix_hint": "Use hmac.compare_digest() or secrets.compare_digest() for secret comparison",
        "test_hint": "Verify secret comparisons use constant-time comparison functions",
    },
    {
        "id": "SEC-012",
        "severity": "HIGH",
        "lang": ["python"],
        "pattern": r"(DEBUG\s*=\s*True|debug\s*=\s*True|app\.debug\s*=\s*True)",
        "description": "Debug mode enabled — exposes stack traces, secrets, and internal state",
        "fix_hint": "Set DEBUG=False in production; use environment variable: DEBUG=os.getenv('DEBUG','false')=='true'",
        "test_hint": "Verify debug mode is off in production config and controlled by environment variables",
    },
    {
        "id": "SEC-013",
        "severity": "MEDIUM",
        "lang": ["python"],
        "pattern": r"hashlib\.(md5|sha1)\(",
        "description": "Weak hash algorithm: MD5/SHA1 are broken for security purposes",
        "fix_hint": "Use hashlib.sha256() or hashlib.sha3_256() for security-sensitive hashing",
        "test_hint": "Verify cryptographic operations use SHA-256 or stronger",
    },
    {
        "id": "SEC-014",
        "severity": "HIGH",
        "lang": ["python"],
        "pattern": r"verify\s*=\s*False",
        "description": "TLS verification disabled — allows man-in-the-middle attacks",
        "fix_hint": "Do not disable TLS verification; fix certificates instead of bypassing checks",
        "test_hint": "Verify no HTTP client calls disable TLS certificate verification",
    },
]
